image: "rust:latest"

before_script:
  - rustup install nightly
  - rustup default nightly

test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose
