[package]
name = "tensor-macros"
version = "0.1.1"
authors = ["Conrad Ludgate <oon@conradludgate.com>"]
edition = "2018"

description = "A compile time optimised tensor library"
repository = "https://github.com/conradludgate/tensor-macros"
license = "MIT"


[dependencies]
